/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#c9e6ff",
        "primary-fixed-dim": "#b1c5ff",
        "surface-tint": "#3d5ca2",
        "on-error-container": "#93000a",
        "outline-variant": "#c4c6d2",
        "surface-container": "#eeeeee",
        "error": "#ba1a1a",
        "primary": "#001a48",
        "outline": "#747782",
        "surface-bright": "#f9f9f9",
        "secondary-container": "#0cb3ff",
        "on-secondary-fixed": "#001e2f",
        "tertiary-fixed-dim": "#b5c7e9",
        "primary-container": "#002d72",
        "surface-container-low": "#f3f3f3",
        "on-surface": "#1a1c1c",
        "surface-container-highest": "#e2e2e2",
        "inverse-primary": "#b1c5ff",
        "on-tertiary-fixed-variant": "#354763",
        "primary-fixed": "#dae2ff",
        "background": "#f9f9f9",
        "on-tertiary-fixed": "#071c35",
        "tertiary-fixed": "#d5e3ff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "tertiary": "#081d36",
        "surface-container-high": "#e8e8e8",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001946",
        "surface": "#f9f9f9",
        "on-secondary-container": "#004261",
        "surface-variant": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f1f1f1",
        "on-primary-fixed-variant": "#224489",
        "on-primary": "#ffffff",
        "surface-dim": "#dadada",
        "on-tertiary-container": "#889aba",
        "on-primary-container": "#7a97e2",
        "on-background": "#1a1c1c",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#004b6f",
        "inverse-surface": "#2f3131",
        "secondary": "#006492",
        "tertiary-container": "#1f324c",
        "secondary-fixed-dim": "#8bceff",
        "on-surface-variant": "#444651"
      },
      fontFamily: {
        "headline": ["Work Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
